### ISSUE TITLE
Synchronize efforts

### ISSUE THREAD

**Issue by lazaridis-com** [lazaridis-com/light-admin#1]
Hi @anegrin, are you interested to synchronize efforts a bit?

I see that you have a organization setup, possibly you enable Issues, too, because issues in the main la repo are

**Comment by anegrin** [comment]
could be, atklab is a customer of mine (i'm a consultant)

we basically enhance lightadmin when we need some feature in new projects so it's really linked to the incoming ones

by now we're done but in the near future we'd like stuff like XXXToMany ordering in forms, image previews in relations etc.

**Comment by lazaridis-com** [comment]
ok, I see. Just if you find the time, see that you cleanup your master (I've given you the instructions and tried them in my fork). And of course no problem if you leave it as is!

**Comment by anegrin** [comment]
yeah thanx but i'd like to keep "fork" as the main github repo becouse this setup works nice with circleci integration (btw circleci is awesome, better than travis IMHO )

**Comment by lazaridis-com** [comment]
ok
