### ISSUE TITLE
Spring Platform 1.1.2

### ISSUE THREAD

**Issue by lazaridis-com** [lazaridis-com/light-admin#3]
On branch spring-platform-1.1.2, the used versions should be changed to become equal with those used in Spring Platform 1.1.2.

This simplifies integration with other spring projects, and of course spring-boot. A possible problem could be the versions which are now higher than within 1.1.2 (changes fetched from @bfcapell fork ).

Code from @akurdyukov can be used, which has spring-data versions identical to spring-boot-1.2.3 (spring-platform-1.2.0).

The version numbers are documented right within the lightadmin-core/pom.xml, int the spring-platform-1.2.0 branch.

(possibly this branch should be created from scratch, with @akurdyukov code)

**Comment by lazaridis-com** [comment]
@bfcapell, it works with spring-boot, see la-team/light-admin#189.

You contribution was essential to achieving this.

**Comment by bfcapell** [comment]
Cool, glad it was useful! Thanks for integrating it!
El dia 13/05/2015 07:11, "Lazaridis" <notifications@github.com> va escriure:

**Comment by lazaridis-com** [comment]
changes from https://github.com/akurdyukov/light-admin/commit/044eeb44d1831c0ead9655fae1b7d40fd8e26c33#diff-04c6e90faac2675aa89e2176d2eec7d8R236 should be integrated to the platform-1.2.0 branch (because they are closer to the versions)

**Comment by lazaridis-com** [comment]
work towards spring-boot-1.2.3 continues on the master branch. @akurdyukov changes were merged there.
